// <auto-generated />
using System;
using Fibonacci;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fibonacci.Migrations
{
    [DbContext(typeof(FibonacciDataContext))]
    [Migration("20201109123741_AddFibFibonacciCreatedTimestamp")]
    partial class AddFibFibonacciCreatedTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fibonacci.TFibonacci", b =>
                {
                    b.Property<Guid>("FibId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FIB_Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("FibCreatedTimestamp")
                        .HasColumnName("FIB_CreatedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("FibInput")
                        .HasColumnName("FIB_Input")
                        .HasColumnType("int");

                    b.Property<long>("FibOutput")
                        .HasColumnName("FIB_Output")
                        .HasColumnType("bigint");

                    b.HasKey("FibId")
                        .HasName("PK_Fibonacci");

                    b.ToTable("T_Fibonacci","sch_fib");
                });
#pragma warning restore 612, 618
        }
    }
}
